[shell]
font_family = "IBM Plex Sans"
niri_overview_type_to_launch_enabled = true
telemetry_enabled = false
corner_radius_scale = 0.0

[theme]
mode = "dark"
source = "builtin"
builtin = "Gruvbox"

[hooks]
theme_mode_changed = "sh ~/.config/noctalia/scripts/sync-system-theme.sh"

[shell.panel]
control_center_placement = "attached"
launcher_placement = "centered"

[shell.shadow]
direction = "down"
alpha = 0.18

[bar.main]
position = "top"
thickness = 28
background_opacity = 0.9
radius = 0
margin_ends = 12
margin_edge = 12
padding = 8
widget_spacing = 2
shadow = false
capsule = true
capsule_fill = "surface_variant"
capsule_border = ""
capsule_radius = 0.0
capsule_padding = 8.0
capsule_opacity = 0.9

start = ["launcher", "wallpaper", "workspaces"]
center = []
end = ["media", "tray", "notifications", "clipboard", "network", "bluetooth", "volume", "battery", "weather", "clock", "control-center", "session"]

[[bar.main.capsule_group]]
id = "signals"
members = ["network", "bluetooth", "volume", "battery"]
fill = "surface_variant"
border = ""
opacity = 0.9
padding = 8.0
radius = 0.0

[[bar.main.capsule_group]]
id = "actions"
members = ["clock", "control-center", "session"]
fill = "surface_variant"
border = ""
opacity = 0.9
padding = 8.0
radius = 0.0

[bar.main.monitor.laptop]
match = "eDP-1"
end = ["media", "tray", "notifications", "clipboard", "network", "bluetooth", "volume", "brightness", "battery", "clock", "control-center", "session"]

[[bar.main.monitor.laptop.capsule_group]]
id = "signals"
members = ["network", "bluetooth", "volume", "brightness", "battery"]
fill = "surface_variant"
border = ""
opacity = 0.9
padding = 8.0
radius = 0.0

[[bar.main.monitor.laptop.capsule_group]]
id = "actions"
members = ["clock", "control-center", "session"]
fill = "surface_variant"
border = ""
opacity = 0.9
padding = 8.0
radius = 0.0

[widget.clock]
format = "{:%d/%m %H:%M}"

[widget.control-center]
custom_image = "/home/yoran/.config/noctalia/nix-snowflake-colours.svg"
custom_image_colorize = false

[notification]
enable_daemon = true

[brightness]
enable_ddcutil = false

[wallpaper]
enabled = false
directory_dark = "/home/yoran/Wallpapers/dark"
directory_light = "/home/yoran/Wallpapers/light"
fill_mode = "crop"

[backdrop]
enabled = false

[weather]
enabled = true
refresh_minutes = 30
unit = "celsius"

[location]
auto_locate = true
